ENABLE_LINTERS: CSS_STYLELINT,HTML_HTMLHINT,HTML_DJLINT,JAVASCRIPT_ES,SPELL_CSPELL,MARKDOWN_MARKDOWNLINT,JSON_NPM_PACKAGE_JSON_LINT,JSON_JSONLINT,JSON_PRETTIER
CSS_STYLELINT_FILE_EXTENSIONS: [".scss"]
