name: Code Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Code Linting
        run: npm run lint
