name: Code Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 16

jobs:
  code-scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: stylelinter          
        uses: actions-hub/stylelint@v1.1.3
