name: Deploy Surge Websites

on: [release, workflow_dispatch]

jobs:
  deploy-betting-template:
    name: Deploy Betting Template
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with: 
          node-version: 16
               
      - name: Install surge
        run: npm install --global surge
      
      - name: Run Surge
        run: surge ./docs/betting-template/build practice-landings-betting-template.surge.sh --token ${{ secrets.SURGE_TOKEN }}
  deploy-headphones:
    name: Deploy Headphones
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with: 
          node-version: 16
               
      - name: Install surge
        run: npm install --global surge
      
      - name: Run Surge
        run: surge ./docs/headphones/build practice-landings-headphones.surge.sh --token ${{ secrets.SURGE_TOKEN }}
 
